- .github/workflows/android-master.yml
The pipeline is based on an docker image which contains java as well as the android sdk.
> Added working pipeline

- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageEditor.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/FaceDetector.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/SmileDetector.kt
We decided that the usage of bitmap instead of android.media.Image was nessesary, because all of our steps need a bitmap, and not a Image anyway
> Switch to bitmap!

- app/src/main/AndroidManifest.xml
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationBroadcastReceiver.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationHandler.kt
- app/src/main/res/values/strings.xml
Not exactly ready to be merged into master - requesting feedback.
> 9 Added class NotificationHandler that is capable of pushing notifications

- app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
I found the reason why two analyzers were running: A missing "!".
> Bugfix: Two analyzers running

- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/BitmapEditorTest.kt
- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/HaarCascadeFaceDetectorTest.kt
- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/detector/FerTFLiteSmileDetectorImplTest.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/BitmapEditor.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/AbstractTFLiteSmileDetector.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/FaceDetector.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/FerTFLiteSmileDetectorImpl.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/SmileDetector.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/facedetectorimpl/HaarCascadeFaceDetector.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/AbstractTFLiteSmileDetector.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/FerTFLiteSmileDetectorImpl.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ImageAnalyzerConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/MainConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/exceptions/InvalidJsonStringException.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationBroadcastReceiver.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationHandler.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/util/YuvToRgbConverter.kt
- build.gradle
- detekt.yml
- Check detekt rules and set to true if useful
- Apply latest detekt rules changes
- Add Doc comments if necessary
- Minor refactoring
> NO TICKET adapt detekt config

- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/HaarCascadeFaceDetectorTest.kt
- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/detector/FerTFLiteSmileDetectorImplTest.kt
Add JUnit compliance to existing tests
> 25 Refactor tests

- app/build.gradle
- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/detector/FerTFLiteSmileDetectorImplTest.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/AboutConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/MainConfig.kt
- Add AboutConfig where credits/privacy/imprint URLs are stored
- Add AboutConfig loading in ConfigManager
- Adapt ConfigManagerTest
- Make detekt compliant
> 33 implement credits/privacy/imprint loader

- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/SettingsConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SettingsFragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/SettingsViewModel.kt
- Add SettingsConfig data class
- Make ConfigManager able to store/load SettingsConfig
- Bind ConfigManager/SettingsConfig to UI by using Observables
> NO TICKET Add settings config

- app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
The only thing to do is set an flag in the main activity
> added flag for keep screen on

- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/CameraActivity.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/MainConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/SecondsConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/SettingsConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/TimerConfig.kt
- Add SettingsConfig and adapt ConfigManager to be using SettingsConfig
- Add some sort of exception handling in CameraActivity when using `ConfigManager.load()`
- Minor refactoring / typo fixes
> 42 Load state machine timer duration from config

- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/FerTFLiteSmileDetectorTest.kt
- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/GoogleMLKitAPIFaceDetectorTest.kt
- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/GoogleMLKitAPISmileDetectorTest.kt
- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/HaarCascadeFaceDetectorTest.kt
- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationHandler.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/util/StateMachineUtil.kt
> renamed CameraActivity to MainActivity

- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/BitmapEditorTest.kt
- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/GoogleMLKitAPIFaceDetectorTest.kt
- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/GoogleMLKitAPISmileDetectorTest.kt
- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/factories/DetectorFactoryTest.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/facedetectorimpl/GoogleMLKitAPIFaceDetector.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/GoogleMLKitAPISmileDetector.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/factories/DetectorFactory.kt
- Make changes in DetectFactory
- Add DetectFactoryTest
- Refactor
> 47 Make DetectFactory load Impls with/without context

- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/AboutConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/HelpFragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
add URL for license, feedback and issues
> 46 bug fixes

- app/src/main/res/menu/overflow_menu.xml
> 58 - Removed Jokes from menu

- app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
the string order  "move your face..." and "Take a breath..." are now fixed
> fixed wrong textes

- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/HaarCascadeFaceDetectorTest.kt
- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/AbstractTFLiteSmileDetector.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/smiledetectorimpl/FerTFLiteSmileDetector.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/AboutConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ImageAnalyzerConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/MainConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/NotificationConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/SettingsConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/TimerConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
- Add Builder in Config classes
- Adapt depending classes/tests
- Remove already resolved TODOs
- Refactor
> NOTICKET Add Builder in Config classes

- app/src/main/AndroidManifest.xml
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/LoadConfigActivity.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SmileFragment.kt
- app/src/main/res/layout/activity_load_config.xml
- app/src/main/res/values/strings.xml
Whenever an file gets opened with the ".sohappy" file-extension, the LoadConfigActivity gets opened. If its an https-Link, the config gets downloaded. if its an file, it gets opened. Then the new config will be checked and applied. Then soHappy gets started.
> Added FileHandler for QR-Codes and Files

- README.md
- Add build/install instructions to README.md
- Link to report
> 64 Update README.md

- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/MainConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/RemoteConfig.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/sync/RemoteSite.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/sync/RemoteSync.kt
- Add RemoteConfig
- Adapt depending classes
- Fix detekt compliance issues
> NOTICKET Remote config

- app/src/main/java/de/hsaugsburg/teamulster/sohappy/LoadConfigActivity.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/ImageAnalyzer.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/analyzer/detector/facedetectorimpl/HaarCascadeFaceDetector.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/CameraFragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ExplanationPagerAdapter.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/HomeFragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/JokesFragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/NoSmileFragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire01Fragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire02Fragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire03Fragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire04Fragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire05Fragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/Questionnaire06Fragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/SettingsFragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/notification/NotificationHandler.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/sync/RemoteSite.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/sync/RemoteSync.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/MeasurementViewModel.kt
delete unused suppress warnings and improved minor issues
> cleanup code

- app/src/androidTest/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManagerTest.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/LoadConfigActivity.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/exceptions/ExceptionHandler.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/fragment/ResultsFragment.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/viewmodel/SettingsViewModel.kt
- app/src/main/res/layout/fragment_results.xml
- Split up load/store function in ConfigManager
- Adjust depending classes and tests
- ResultsFragment, finishButton: Set isClickable to false while loading
> Minor fixes

- README.md
- app/build.gradle
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/MainActivity.kt
- app/src/main/java/de/hsaugsburg/teamulster/sohappy/config/ConfigManager.kt
- Update app/build.gradle
- Update README.md
- Add TODO
- Minor fixes
> Add v1.0-rc02
